//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mugshots.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class criminal_list
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string image_path { get; set; }
        public string Arrest_Agency { get; set; }
        public string Arrest_Date { get; set; }
        public string Arrest_Time { get; set; }
        public string DOB { get; set; }
        public string Eyes { get; set; }
        public string Hair { get; set; }
        public string Build { get; set; }
        public string Current_Age { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Charge_Description { get; set; }
        public string Class { get; set; }
        public string Court { get; set; }
        public string DISP { get; set; }
        public string Charge_Type { get; set; }
    }
}
